<!DOCTYPE html>
<html lang="en" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
  <meta charset="utf-8">
  <meta name="x-apple-disable-message-reformatting">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="format-detection" content="telephone=no, date=no, address=no, email=no">
  <!--[if mso]>
    <xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch></o:OfficeDocumentSettings></xml>
    <style>
      td,th,div,p,a,h1,h2,h3,h4,h5,h6 {font-family: "Segoe UI", sans-serif; mso-line-height-rule: exactly;}
    </style>
  <![endif]-->
  
    <title>The Website Weekly Newsletter</title>
  
    <style>/* Your custom CSS resets for email */

/*
 * Here is where you can add your global CSS resets.
*/

body {
  margin: 0;
  padding: 0;
  width: 100%;
  word-break: break-word;
  -webkit-font-smoothing: antialiased;
}

img {
  line-height: 100%;
  max-width: 100%;
  vertical-align: middle;
  border: 0;
}

/* Tailwind components that are generated by plugins */

/**
 * @import here any custom components - classes that you'd want loaded
 * before the Tailwind utilities, so that the utilities could still
 * override them.
*/

/* Tailwind utility classes */

.bg-white {
  background-color: #ffffff !important;
}

.bg-gray-100 {
  background-color: #f3f4f6 !important;
}

.bg-gray-200 {
  background-color: #e5e7eb !important;
}

.bg-gray-300 {
  background-color: #d1d5db !important;
}

.bg-blue-500 {
  background-color: #3b82f6 !important;
}

.bg-indigo-800 {
  background-color: #3730a3 !important;
}

.hover-bg-blue-600:hover {
  background-color: #2563eb !important;
}

.hover-bg-indigo-700:hover {
  background-color: #4338ca !important;
}

.bg-top {
  background-position: top !important;
}

.bg-no-repeat {
  background-repeat: no-repeat !important;
}

.bg-cover {
  background-size: cover !important;
}

.rounded {
  border-radius: 4px !important;
}

.border {
  border-width: 1px !important;
}

.cursor-default {
  cursor: default !important;
}

.block {
  display: block !important;
}

.inline-block {
  display: inline-block !important;
}

.table {
  display: table !important;
}

.hidden {
  display: none !important;
}

.font-sans {
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important;
}

.font-semibold {
  font-weight: 600 !important;
}

.h-32 {
  height: 32px !important;
}

.h-48 {
  height: 48px !important;
}

.h-64 {
  height: 64px !important;
}

.h-px {
  height: 1px !important;
}

.text-xs {
  font-size: 12px !important;
}

.text-sm {
  font-size: 14px !important;
}

.text-base {
  font-size: 16px !important;
}

.text-lg {
  font-size: 18px !important;
}

.text-xl {
  font-size: 20px !important;
}

.text-2xl {
  font-size: 24px !important;
}

.text-4xl {
  font-size: 36px !important;
}

.leading-24 {
  line-height: 24px !important;
}

.leading-64 {
  line-height: 64px !important;
}

.leading-px {
  line-height: 1px !important;
}

.leading-full {
  line-height: 100% !important;
}

.m-0 {
  margin: 0 !important;
}

.mb-4 {
  margin-bottom: 4px !important;
}

.mb-16 {
  margin-bottom: 16px !important;
}

.mb-24 {
  margin-bottom: 24px !important;
}

.max-w-full {
  max-width: 100% !important;
}

.p-0 {
  padding: 0 !important;
}

.p-24 {
  padding: 24px !important;
}

.p-48 {
  padding: 48px !important;
}

.py-16 {
  padding-top: 16px !important;
  padding-bottom: 16px !important;
}

.py-24 {
  padding-top: 24px !important;
  padding-bottom: 24px !important;
}

.px-24 {
  padding-left: 24px !important;
  padding-right: 24px !important;
}

.py-32 {
  padding-top: 32px !important;
  padding-bottom: 32px !important;
}

.px-48 {
  padding-left: 48px !important;
  padding-right: 48px !important;
}

.pr-16 {
  padding-right: 16px !important;
}

.pl-16 {
  padding-left: 16px !important;
}

.pb-32 {
  padding-bottom: 32px !important;
}

.text-left {
  text-align: left !important;
}

.text-center {
  text-align: center !important;
}

.text-black {
  color: #000000 !important;
}

.text-white {
  color: #ffffff !important;
}

.text-gray-500 {
  color: #6b7280 !important;
}

.text-gray-600 {
  color: #4b5563 !important;
}

.text-gray-800 {
  color: #1f2937 !important;
}

.text-blue-500 {
  color: #3b82f6 !important;
}

.hover-text-blue-400:hover {
  color: #60a5fa !important;
}

.italic {
  font-style: italic !important;
}

.uppercase {
  text-transform: uppercase !important;
}

.underline {
  text-decoration: underline !important;
}

.no-underline {
  text-decoration: none !important;
}

.hover-underline:hover {
  text-decoration: underline !important;
}

.hover-no-underline:hover {
  text-decoration: none !important;
}

.w-48 {
  width: 48px !important;
}

.w-600 {
  width: 600px !important;
}

.w-full {
  width: 100% !important;
}

.w-1-2 {
  width: 50% !important;
}

/* Your custom utility classes */

/*
 * Here is where you can define your custom utility classes.
*/

.mso-leading-exactly {
  mso-line-height-rule: exactly;
}

@media (max-width: 600px) {
  .sm-inline-block {
    display: inline-block !important;
  }

  .sm-h-32 {
    height: 32px !important;
  }

  .sm-leading-32 {
    line-height: 32px !important;
  }

  .sm-leading-40 {
    line-height: 40px !important;
  }

  .sm-px-0 {
    padding-left: 0 !important;
    padding-right: 0 !important;
  }

  .sm-px-16 {
    padding-left: 16px !important;
    padding-right: 16px !important;
  }

  .sm-px-24 {
    padding-left: 24px !important;
    padding-right: 24px !important;
  }

  .sm-py-32 {
    padding-top: 32px !important;
    padding-bottom: 32px !important;
  }

  .sm-pb-32 {
    padding-bottom: 32px !important;
  }

  .sm-w-16 {
    width: 16px !important;
  }

  .sm-w-full {
    width: 100% !important;
  }
}</style>
  
</head>
<body class="bg-gray-100">
  
    <div class="hidden">👀 Lorem, ipsum, and much dolor in this week's edition&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
      &#160;&#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &#847; &zwnj;
      &#160;&#847; &#847; &#847; &#847; &#847; </div>
  <div role="article" aria-roledescription="email" aria-label="The Website Weekly Newsletter" lang="en">
    
    <table class="w-full font-sans" cellpadding="0" cellspacing="0" role="presentation">
      <tr>
        <td align="center" class="bg-gray-100 sm-px-16">
          <table class="w-600 sm-w-full" cellpadding="0" cellspacing="0" role="presentation">
            <tr>
              <td class="p-48 sm-py-32 sm-px-24 text-center">
                <a href="https://maizzle.com">
                  <img src="images/maizzle.png" width="75" alt="Maizzle">
                </a>
              </td>
            </tr>
            <tr>
              <td class="bg-top bg-no-repeat bg-cover rounded text-left" style="background-image: url('https://images.unsplash.com/photo-1565932887479-b18108f07ffd?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1200&amp;q=80');">
                <!--[if mso]>
<v:image src="https://images.unsplash.com/photo-1565932887479-b18108f07ffd?ixlib=rb-1.2.1&amp;ixid=eyJhcHBfaWQiOjEyMDd9&amp;auto=format&amp;fit=crop&amp;w=1200&amp;q=80" xmlns:v="urn:schemas-microsoft-com:vml" style="width:600px;height:400px;" />
<v:rect fill="false" stroke="false" style="position:absolute;width:600px;height:400px;">
<v:textbox inset="0,0,0,0"><div><![endif]-->

                  <div class="leading-64 sm-h-32">&zwnj;</div>
                  <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                    <tr>
                      <td class="w-48 sm-w-16"></td>
                      <td>
                        <h1 class="m-0 mb-16 text-4xl text-white sm-leading-40">Lorem ipsum dolor</h1>
                        <p class="m-0 text-white text-lg leading-24">Consectetur esse cupidatat in aliqua pariatur anim pariatur dolor nisi. Adipisicing elit labore nisi ullamco qui sint cillum commodo nisi velit sunt dolore.</p>
                        <div class="leading-64 sm-h-32">&zwnj;</div>
                        <div class="leading-full">
                          <a href="https://example.com" class="inline-block py-16 px-24 rounded text-base font-semibold text-center no-underline text-white bg-indigo-800 hover-bg-indigo-700">
                            <!--[if mso]><i style="letter-spacing: 24px; mso-font-width: -100%; mso-text-raise:30px;">&#8202;</i><![endif]-->
                            <span style="mso-text-raise: 16px;">Read more &rarr;</span>
                            <!--[if mso]><i style="letter-spacing: 24px; mso-font-width: -100%;">&#8202;</i><![endif]-->
                          </a>
                        </div>
                      </td>
                      <td class="w-48 sm-w-16"></td>
                    </tr>
                  </table>
                  <div class="leading-64 sm-h-32">&zwnj;</div>
                
<!--[if mso]></div></v:textbox></v:rect><![endif]-->

              </td>
            </tr>
            <tr>
              <td class="h-32"></td>
            </tr>
            <tr>
              <td class="w-full px-24 sm-px-0 text-left">
                <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                  <tr>
                    <td class="w-full pb-32 sm-w-full sm-inline-block">
                      <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                        <tr>
                          <td class="p-24 bg-white rounded">
                            <p class="m-0 mb-4 text-sm text-gray-500">2 Feb, 2020</p>
                            <h2 class="m-0 mb-24 text-2xl leading-24">Sit aliqua reprehenderit qui veniam culpa.</h2>
                            <p class="m-0 mb-24 text-base text-gray-800">Ex consequat deserunt id cupidatat exercitation irure commodo. Dolor et est irure elit cupidatat laborum veniam amet eiusmod Lorem ex ea do aliqua. Ipsum Lorem nulla sit aliqua quis veniam magna...</p>
                            <a href="https://example.com" class="text-base text-blue-500 hover-text-blue-400 no-underline">Read more &rarr;</a>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td class="w-full px-24 sm-px-0 text-left">
                <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                  <tr>
                    <td class="w-1-2 pr-16 sm-px-0 sm-pb-32 sm-w-full sm-inline-block">
                      <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                        <tr>
                          <td class="p-24 bg-white rounded">
                            <p class="m-0 mb-4 text-sm text-gray-500">3 Feb, 2020</p>
                            <h2 class="m-0 mb-24 text-2xl leading-24">Do ullamco reprehenderit ut dolor.</h2>
                            <p class="m-0 mb-24 text-base text-gray-800">Consectetur veniam ipsum ea sit est do voluptate laboris...</p>
                            <a href="https://example.com" class="text-base text-blue-500 hover-text-blue-400 no-underline">Read more &rarr;</a>
                          </td>
                        </tr>
                      </table>
                    </td>
                    <td class="w-1-2 pl-16 sm-px-0 sm-w-full sm-inline-block">
                      <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                        <tr>
                          <td class="p-24 bg-white rounded">
                            <p class="m-0 mb-4 text-sm text-gray-500">4 Feb, 2020</p>
                            <h2 class="m-0 mb-24 text-2xl leading-24">Sunt in do sunt officia nisi enim qui eiusmod.</h2>
                            <p class="m-0 mb-24 text-base text-gray-800">Nulla officia mollit ipsum eiusmod excepteur ea...</p>
                            <a href="https://example.com" class="text-base text-blue-500 hover-text-blue-400 no-underline">Read more &rarr;</a>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td class="h-64 sm-h-32"></td>
            </tr>
            <tr>
              <td class="px-48 sm-px-24 text-left">
                <h3 class="m-0 text-base font-semibold text-gray-500 uppercase">From the archives</h3>
                <div class="leading-24">&zwnj;</div>
                <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                  <tr>
                    <td>
                      <h4 class="m-0 mb-4 text-xl font-semibold">
                        <a href="https://example.com" class="text-blue-500 hover-text-blue-400 no-underline">Lorem velit tempor qui</a>
                      </h4>
                      <p class="m-0 text-gray-500">Aliquip excepteur sint voluptate Lorem nisi deserunt consequat...</p>
                      <table class="w-full" cellpadding="0" cellspacing="0" role="presentation">
                        <tr>
                          <td class="py-24">
                            <div class="bg-gray-300 h-px leading-px">&zwnj;</div>
                          </td>
                        </tr>
                      </table>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <h4 class="m-0 mb-4 text-xl font-semibold">
                        <a href="https://example.com" class="text-blue-500 hover-text-blue-400 no-underline">Lorem velit tempor qui</a>
                      </h4>
                      <p class="m-0 text-gray-500">Aliquip excepteur sint voluptate Lorem nisi deserunt consequat...</p>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td class="h-64 sm-h-32"></td>
            </tr>
            <tr>
              <td class="px-48 sm-px-24 py-16 bg-cool-gray-300 rounded text-left">
                <p class="m-0 text-sm text-cool-gray-500">
                  You are receiving this email because you signed up for Website Newsletter Weekly.
                  You can <a href="https://example.com" class="text-blue-500 hover-text-blue-400 no-underline">unsubscribe</a> at any time.
                </p>
              </td>
            </tr>
            <tr>
              <td class="h-48 sm-h-32"></td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  
  </div>
</body>
</html>

